---
version: "3.8"

services:
  nginx-http-flv-module:
    build: .
    container_name: nginx
    ports:
      - 5239:80
      - 1935:1935
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/appdata/nginx:/www
    restart: always
